---
title: "Elections France 2017 Data Wrangling"
output:  github_document
---
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
```


```{r}
df_votes.2017<-read.csv('data/DOI/Pres_Tour1_2017.csv',stringsAsFactors = F,sep=';')
```

Clean the mess with the votes results (the score are ranked per columns !!!)

```{r}


colos_Exp<-grep('X..Voix.Exp',colnames(df_votes.2017),value = T)
colos_name<-grep('Nom',colnames(df_votes.2017),value = T)
colos_Voix<-grep('^Voix',colnames(df_votes.2017),value = T)


filtered_df_pres<-df_votes.2017 %>% select_(.dots = c(colos_Exp,colos_name,colos_Voix,"Code.de.la.commune", "Libellé.de.la.commune","Code.du.département","Libellé.du.département","Votants","Inscrits","Abstentions" ,"Exprimés","X..Abs.Ins","X..Exp.Vot"))

gather_name<-filtered_df_pres %>% gather(key,'Nom',starts_with('Nom')) 
gather_scores<- filtered_df_pres%>% gather(key,'Score',starts_with('X..Voix.Exp'))
gather_voix<- filtered_df_pres%>% gather(key,'Voix',starts_with('Voix'))


gather_name_scores<- data.frame(select(gather_scores, Score), select(gather_name,Nom,Code.de.la.commune, Libellé.de.la.commune,Code.du.département,Libellé.du.département,Votants,Inscrits,Abstentions,Exprimés,X..Abs.Ins,X..Exp.Vot),select(gather_voix,Voix))

df_votes.2017<-gather_name_scores

#ggplot(df_votes.2017,aes(x=Nom,y=Score, col=Nom))+ geom_boxplot()

```
```{r}
df_votes.2017 %>% filter(Code.du.département==73  &  grepl("Peis",Libellé.de.la.commune))
```

top LE PEN :
```{r}
df_votes.2017 %>% filter(Nom=='LE PEN' & Code.du.département==75)  %>% arrange(desc(Votants))
```

Spread candidate names :
```{r}
df_votes.2017<- df_votes.2017   %>% group_by(Code.du.département,Libellé.du.département,
                                       Code.de.la.commune,Libellé.de.la.commune,Nom,Votants,Inscrits,Abstentions,Exprimés,X..Abs.Ins,X..Exp.Vot) %>% summarise(Mean_Score=mean(Score)) %>% spread(Nom,Mean_Score)
filter(df_votes.2017,grepl('Vichy',Libellé.de.la.commune)& Code.du.département==3)

write.csv(df_votes.2017,'data/DOI/pres_1erTour_2017_commune_candidat.csv')

```


