---
title: "French elections _ Cartograms"
output: html_notebook
---



```{r}
library(dplyr)
library(tidyr)
library(stringr)
```

# Create a data frame with results aggregated per Departement :
```{r}
df<-read.csv('data/DOI/Presidentielle_2017_Resultats_Communes_Tour_1_no_arrondissements75_13_69.csv', stringsAsFactors = FALSE)
str(df)
```

Clean the mess with the votes results (the score are ranked per columns !!!)

```{r}
colos_Exp<-grep('X..Voix.Exp',colnames(df),value = T)
colos_name<-grep('Nom',colnames(df),value = T)
colos_Voix<-grep('^Voix',colnames(df),value = T)


filtered_df_pres<-df %>% select_(.dots = c(colos_Exp,colos_name,colos_Voix,"Code.de.la.commune", "Libellé.de.la.commune","Code.du.département","Libellé.du.département","Votants","Inscrits","Abstentions" ,"Exprimés","X..Abs.Ins","X..Exp.Vot"))

gather_name<-filtered_df_pres %>% gather(key,'Nom',starts_with('Nom')) 
gather_scores<- filtered_df_pres%>% gather(key,'Score',starts_with('X..Voix.Exp'))
gather_voix<- filtered_df_pres%>% gather(key,'Voix',starts_with('Voix'))


gather_name_scores<- data.frame(select(gather_scores, Score), select(gather_name,Nom,Code.de.la.commune, Libellé.de.la.commune,Code.du.département,Libellé.du.département,Votants,Inscrits,Abstentions,Exprimés,X..Abs.Ins,X..Exp.Vot),select(gather_voix,Voix))

df_votes.2017<-gather_name_scores

#ggplot(df_votes.2017,aes(x=Nom,y=Score, col=Nom))+ geom_boxplot()

```

```{r}
df_votes.2017 %>% filter(Code.du.département==73  &  grepl("Peis",Libellé.de.la.commune))
```

top LE PEN :
```{r}
df_votes.2017 %>% filter(Nom=='LE PEN' & Code.du.département==75)  %>% arrange(desc(Votants))
```

Spread candidate names :
```{r}
df_votes.2017<- df_votes.2017   %>% group_by(Code.du.département,Libellé.du.département,
                                       Code.de.la.commune,Libellé.de.la.commune,Nom,Votants,Inscrits,Abstentions,Exprimés,X..Abs.Ins,X..Exp.Vot) %>% summarise(Sum_Voix=sum(Voix)) %>% spread(Nom,Sum_Voix)
filter(df_votes.2017,grepl('Vichy',Libellé.de.la.commune)& Code.du.département==3)

```


```{r}
names(df_votes.2017)[names(df_votes.2017) == "LE PEN"] <- "LE.PEN"
names(df_votes.2017)[names(df_votes.2017) == "DUPONT-AIGNAN"] <- "DUPONT.AIGNAN"

candidats<-c("ARTHAUD","ASSELINEAU","CHEMINADE","DUPONT.AIGNAN", "FILLON","HAMON","LASSALLE","LE.PEN","MACRON","MÉLENCHON","POUTOU")

groupy_departement<- df_votes.2017 %>% group_by(Code.du.département)  %>% summarise_at(c(candidats,"Exprimés"),funs(total_voix=sum(.), ratio_voix=sum(.)/sum(Exprimés)))
write.csv(groupy_departement,'data/DOI/pres_1erTour_2017_par_departement_candidat.csv')
View(groupy_departement)
```

