---
title: "Elections France 2017 Maps"
output:  github_document
---

```{r}
library(sp)
library(rgdal)
library(dplyr)
library(tidyr)
library(stringr)
library(gridExtra)

library(RColorBrewer)
library(classInt)
library(plotrix)    # Créer des échelles de couleurs

library(cartogram)
library(tmap)
library(maptools)
```

```{r}
# Emplacement de l'archive décompressée
pathToShp_dept <- "data/GEOFLA_DEPT/1_DONNEES_LIVRAISON_2016-06-00235/GEOFLA_2-2_SHP_LAMB93_FR-ED161/DEPARTEMENT"
```

```{r}

df.elections_2017_departements<-read.csv('data/DOI/pres_1erTour_2017_par_departement_candidat.csv')
df.elections_2017_departements<-df.elections_2017_departements %>%  mutate(CODE_DEPT=str_pad(Code.du.département, 2, pad = "0"))
df.elections_2017_departements$CODE_DEPT<- as.factor(df.elections_2017_departements$CODE_DEPT)
ratio_cols <- grep('ratio',colnames(df.elections_2017_departements))
df.elections_2017_departements <- df.elections_2017_departements %>% mutate_at(ratio_cols, funs(percent = round(.*100,0)))

```
# Lecture des pays et sélection de l'Europe
```{r}
# Lecture des départements
departements <- readOGR(dsn=pathToShp_dept,  layer="DEPARTEMENT")

# Lecture des limites départementales pour sélectionner les frontières
frontieres <- readOGR(dsn=pathToShp_dept,  layer="LIMITE_DEPARTEMENT")
frontieres <- frontieres[frontieres$NATURE %in% c('Fronti\xe8re internationale','Limite c\xf4ti\xe8re'),]

# Lecture des pqys europeens
europe <- readOGR(dsn="data/countries/", layer="ne_10m_admin_0_countries")
europe<- europe[europe$REGION_UN=="Europe",]
# Projection en Lambert 93
europe <- spTransform(europe, CRS("+init=epsg:2154"))
```



```{r}
dim(departements@data)
str(departements@data)
```



```{r}

departements@data <- left_join(departements@data, df.elections_2017_departements, by="CODE_DEPT")
str(departements@data)
```
# Cartogram
```{r}
# construct cartogram
dept_cartogram <- cartogram(departements, "Exprimés_total_voix", itermax=5)

```

```{r}
# plot it
tm_shape(dept_cartogram) + tm_fill("LE.PEN_ratio_voix_percent", style="quantile",palette="Reds" ,title = "LE PEN (%)") + 
  tm_borders() + tm_layout(frame=F)+ tm_credits("Related to population - Data @ Ministère de l'Intérieur", position = c("right", "bottom")) +tm_layout(title="First round", 
	title.position = c("left", "top"), 
	legend.position = c("left", "bottom"), 
	frame = FALSE, 
	inner.margins = c(0.1, 0.1, 0.05, 0.05))

# plot it
tm_shape(dept_cartogram) + tm_fill("MACRON_ratio_voix_percent", style="quantile",palette="Blues", title = "MACRON (%)") + 
  tm_borders() + tm_layout(frame=F)+tm_credits("Related to population - Data @ Ministère de l'Intérieur", position = c("right", "bottom"))  +tm_layout(title="First round", 
	title.position = c("left", "top"), 
	legend.position = c("left", "bottom"), 
	frame = FALSE, 
	inner.margins = c(0.1, 0.1, 0.05, 0.05))
```
`
