---
title: "Elections France 2017 Data Merge"
output:  github_document
---
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(GGally)
library(ggcorrplot)
```



```{r}
df_communes<- read.csv('data/DOI/OGR_Communes.csv',colClasses=c(INSEE_COM='character',CODE_COM='character',CODE_DEPT='character',CODE_ARR='character')) %>% select(CODE_COM,INSEE_COM,NOM_COM,CODE_ARR,CODE_DEPT,NOM_DEPT,CODE_REG,NOM_REG,POPULATION)
df_communes<-df_communes %>%  unite(CODGEO_ARR_NO,CODE_DEPT,CODE_ARR,sep='',remove=FALSE)
df_communes<-df_communes %>%  mutate(CODE_COM=str_pad(CODE_COM, 3, pad = "0"))
df_communes<-df_communes %>%  mutate(CODE_ARR=str_pad(CODE_ARR, 3, pad = "0"))
df_communes<-df_communes %>%  unite(CODGEO_ARR,CODE_DEPT,CODE_ARR,sep = '')


str(df_communes)

```
### Combine with votes :

```{r}
candidats<-c("ARTHAUD","ASSELINEAU","CHEMINADE","DUPONT.AIGNAN","FILLON","HAMON","LASSALLE","LE.PEN","MACRON","MÉLENCHON","POUTOU")

df_votes.2017<-read.csv('data/DOI/pres_1erTour_2017_commune_candidat.csv',stringsAsFactors = F)
df_votes.2017<-df_votes.2017 %>%  mutate(CODE_COM=str_pad(Code.de.la.commune, 3, pad = "0"))
df_votes.2017<-df_votes.2017 %>%  mutate(CODE_DEPT=str_pad(Code.du.département, 2, pad = "0"))
df_votes.2017<-df_votes.2017 %>%  unite(GEOCODE_COM,CODE_DEPT,CODE_COM,sep = '')
df_votes.2017<- df_votes.2017 %>% select(-Code.de.la.commune,-Libellé.de.la.commune,-Code.du.département,-Libellé.du.département)

df.all<-merge(df_communes,df_votes.2017,by.x='INSEE_COM',by.y='GEOCODE_COM',all.x=TRUE)
str(df.all)
df.all %>% filter(INSEE_COM=='32009')
```

### Combine with Population and add Unemployment rate

```{r}

df.emploi.COM<-read.csv('data/DOI/base_cc_emploi_pop_active_13_COM.csv',stringsAsFactors = F, colClasses=c(CODGEO='character'))
df.emploi.COM<- df.emploi.COM %>% mutate(CODGEO=str_pad(CODGEO, 5, pad = "0"))

add_employment_stats <- function(df){
 df<- df %>% select(CODGEO,P13_ACT1564,P13_ACT1524,P13_ACT2554,P13_ACT5564,P13_CHOM1564
,P13_HCHOM1564,P13_HCHOM1524,P13_HCHOM2554,P13_HCHOM5564,P13_FCHOM1564,P13_FCHOM1524,P13_FCHOM2554,P13_FCHOM5564,C13_ACT1564_CS1,C13_ACT1564_CS2,C13_ACT1564_CS3,C13_ACT1564_CS4,C13_ACT1564_CS5,C13_ACT1564_CS6,P13_ETUD1564,P13_RETR1564)

df <- df %>% mutate(NoJob_all=P13_CHOM1564/P13_ACT1564)
df <- df %>%mutate(NoJob_1524=(P13_HCHOM1524+P13_FCHOM1524)/P13_ACT1524)
df <- df %>%mutate(NoJob_2554=(P13_HCHOM2554+P13_FCHOM2554)/P13_ACT2554)
df <- df %>%mutate(NoJob_5564=(P13_HCHOM5564+P13_FCHOM5564)/P13_ACT5564)
df <- df %>% mutate(Job_AGRO=C13_ACT1564_CS1/P13_ACT1564)
df <- df %>% mutate(Job_ARTISAN=C13_ACT1564_CS2/P13_ACT1564)
df <- df %>% mutate(Job_CADRE=C13_ACT1564_CS3/P13_ACT1564)
df <- df %>% mutate(Job_INTERMED=C13_ACT1564_CS4/P13_ACT1564)
df <- df %>% mutate(Job_EMPLOYE=C13_ACT1564_CS5/P13_ACT1564)
df <- df %>% mutate(Job_OUVRIER=C13_ACT1564_CS6/P13_ACT1564)
df <- df %>% mutate(Etudiants=P13_ETUD1564/P13_ACT1564)
df <- df %>% mutate(Retraites=P13_RETR1564/P13_ACT1564) 

df<-df %>% select(-matches('P13|C13'))


return(df)
}

df.emploi.COM<-add_employment_stats(df.emploi.COM)
df.all<-merge(df.all,df.emploi.COM,by.x='INSEE_COM',by.y='CODGEO',suffixes=c('','_COM'),all.x=TRUE)


# compute value per ARR
#df.all <- df.all %>% group_by(CODGEO_ARR) %>% mutate_at(vars(matches('Job')),funs(total=sum(.,na.rm=TRUE)))

df.all %>% filter(grepl('ROSTR',NOM_COM))
df.all %>% filter(grepl('SAINT-NICOLAS-DU-PELEM',NOM_COM)) %>% gather()


```

# Add Incomes indicators
## per town

```{r}
df.income.COM<-read.csv('data/DOI/FILO_DEC_COM.csv') %>% select(CODGEO,Q213,Q3_Q1,RD,GI13)


str(df.income.COM)
df.all<-merge(df.all,df.income.COM,by,by.x='INSEE_COM',by.y='CODGEO',all.x=TRUE)


sum(is.na(df.all$Q213))
dim(df.all)



```

## per County and replace missing town incomes by county incomes.
```{r}
df.income.ARR<-read.csv('data/DOI/FILO_DEC_ARR.csv') %>% select(CODGEO,Q213,Q3_Q1,RD,GI13)

df.all<- merge(df.all,df.income.ARR,by.x="CODGEO_ARR_NO",by.y='CODGEO',all.x=TRUE,suffixes=c('','_ARR'))

sum(is.na(df.all$Q213_ARR))
sum(is.na(df.all$Q213))
df.all<-df.all %>% mutate(Q213=ifelse(is.na(Q213),Q213_ARR,Q213))
sum(is.na(df.all$Q213))
```

# Add foreigners

```{r}

# add ratio of foreigners
df.foreigners<-read.csv('data/DOI/BTX_TD_NAT1_2013.csv')
colnames(df.foreigners)
df.foreigners%>%  select(contains('INATC'))
df.foreigners <- df.foreigners %>% mutate(total_pop= df.foreigners %>%rowwise() %>% select(contains('INATC')) %>% rowSums())
df.foreigners <- df.foreigners %>% mutate(total_foreigners= df.foreigners %>%rowwise() %>% select(contains('INATC2')) %>% rowSums())
df.foreigners <- df.foreigners %>% mutate(ratio_foreigners= total_foreigners/total_pop)
df.foreigners %>% filter(CODGEO=='01001') %>% gather()
df.foreigners <- df.foreigners %>% select(CODGEO,ratio_foreigners)

df.all<-merge(df.all,df.foreigners,by.x='INSEE_COM',by.y='CODGEO')

df.all %>% filter(grepl('PARIS',NOM_COM)) %>% select(ratio_foreigners)

```

## Add migrations

```{r}

df.immigrants<-read.csv('data/DOI/BTX_TD_IMG1A_2013.csv')
colnames(df.foreigners)
df.immigrants%>%  select(contains('INATC'))
df.immigrants <- df.immigrants %>% mutate(total_pop= df.immigrants %>%rowwise() %>% select(contains('IMMI')) %>% rowSums())
df.immigrants <- df.immigrants %>% mutate(total_immigrants= df.immigrants %>%rowwise() %>% select(contains('IMMI1')) %>% rowSums())
df.immigrants <- df.immigrants %>% mutate(ratio_immigrants= total_immigrants/total_pop)
df.immigrants %>% filter(CODGEO=='01001') %>% gather()
df.immigrants <- df.immigrants %>% select(CODGEO,ratio_immigrants)

df.all<-merge(df.all,df.immigrants,by.x='INSEE_COM',by.y='CODGEO')

df.all %>% filter(grepl('VENDOME',NOM_COM)) %>% select(contains('ratio'))

```

# Add miscellaneous features (such as number of Shop, Camping, Hotels)
```{r}

df_misc.param<-read.csv('data/DOI/MDB-INSEE-V2.csv',stringsAsFactors = F)
df.all<-merge(df.all,df_misc.param,by.x='INSEE_COM',by.y='CODGEO',all.x=TRUE)


```

```{r}
df.all<-merge(df.all,df_revenus_pauvrete_ARR,by.x='ARR',by.y='CODGEO',suffixes = c('','_ARR'))
df.all<-merge(df.all,df_revenus_ARR,by.x='ARR',by.y='CODGEO',by='CODGEO',suffixes = c('','_ARR'))

df.all %>% filter(INSEE_COM=="32009")%>% select(Q213,Q213_ARR, Q3_Q1,Q3_Q1_ARR)
```

Focus on one city :
```{r}
df.all %>% filter(INSEE_COM==22007) %>% gather()
```


```{r}

corr <- round(cor(df.all %>% select(one_of(c(candidats,"Taux.étudiants","POP_Active_Male_NoJob","POP_Active_Female_NoJob")))%>% na.omit()),1)

# Plot
ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = FALSE, 
           lab_size = 3, 
           method="square", 
           colors = c("cyan4", "white", "red3"), 
           title="Correlogram of Selected Features", 
           ggtheme=theme_bw)
```

```{r}
ggplot(df.all,aes(x=Score.PIB)) + geom_histogram(bins = 100)
ggplot(df.all,aes(x=P11_POP,y=P11_POP,na.rm=T)) + geom_boxplot()
df.all[which.min(df.all$P11_POP),]
summary(df.all$P11_POP)

```

### Clean features and save
```{r}
# Remove demographic classes data
df.all.clean<-df.all %>% select(-contains('C11')) %>% select(-contains('P11'))

# add Ratio

Nb.Columns<- grep('Nb.',colnames(df.all.clean),value = T)
Ratio.Nb <- gsub("Nb.", "Ratio.", Nb.Columns)

df.all.clean<-df.all.clean %>% mutate_each(funs(ratio=log(./Population+1)),contains('Nb.'))

write.csv(df.all.clean,'data/DOI/elections_2017_First_round.csv')

```

```{r}
bretagne<-df.all.clean %>% filter(REG==24) %>% filter(!is.na(Q3_Q1))
bretagne$extremes<-bretagne$LE.PEN+bretagne$MÉLENCHON
dim(bretagne)
model1<-lm(LE.PEN~. ,data=bretagne %>%select(matches('LE.PEN|NoJob|Q213|Q3_Q1|GI13|RD|Score.PIB|_ratio|Population')))
summary(model1)
```

```{r}
ggplot(df.all.clean  %>% filter(REG %in% c(32,53,93,44)) %>% filter(Population>10),aes(x=Q3_Q1,y=LE.PEN,col=NCC))+geom_jitter(alpha=.5) #+geom_smooth(method = 'lm')
ggplot(df.all.clean  %>% filter(REG %in% c(93)) ,aes(x=(Q213),y=(LE.PEN),col=NCC))+geom_jitter(alpha=.3) #+geom_smooth(method = 'lm')
```

```{r}
ggplot(df.all.clean %>% filter(Q213<30000) %>% filter(REG==53),aes(x=Q213,y=Q3_Q1,col=LE.PEN))+ geom_jitter(alpha=1)+scale_color_gradientn(colours = rainbow(5))
```

